on-unmatched = "info"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]
excludes = ["packages/**/generated.nix", "overlays/**/generated.nix"]

[formatter.yaml]
command = "yamlfmt"
includes = ["*.yml"]
excludes = [".pre-commit-config.yml"]
