---
- name: Common tasks
  tags: [common, "common:setup"]
  block:
    - name: Configure timezone
      ansible.builtin.include_tasks: timezone.yml
    - name: Setup packages (Debian/Ubuntu)
      ansible.builtin.include_tasks: packages/debian.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Configure SSH
      ansible.builtin.include_tasks: ssh.yml
