- name: Traefik
  tags: [traefik, traefik:setup]
  become: yes
  block:
    - name: Create traefik directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755
      loop:
        - "{{ traefik_stack_dir }}"
        - "{{ traefik_data_dir }}"

    - name: Stat acme.json
      ansible.builtin.stat:
        path: "{{ traefik_data_dir }}/acme.json"
      register: acme_json_stat

    - name: Remove acme.json if it's a directory
      ansible.builtin.file:
        path: "{{ traefik_data_dir }}/acme.json"
        state: absent
      when: acme_json_stat.stat.exists and acme_json_stat.stat.isdir

    - name: Create acme.json if it doesn't exist
      ansible.builtin.file:
        path: "{{ traefik_data_dir }}/acme.json"
        state: touch
        owner: root
        group: root
        mode: 0600
        modification_time: preserve
        access_time: preserve

    - name: Create traefik Docker network
      community.docker.docker_network:
        name: traefik
        state: present

    - name: Deploy traefik.yml static config
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: "{{ traefik_data_dir }}/traefik.yml"
        owner: root
        group: root
        mode: 0644
      notify: restart traefik

- name: Traefik deploy
  tags: [traefik, traefik:deploy]
  become: yes
  block:
    - name: Deploy compose file
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ traefik_stack_dir }}/docker-compose.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Deploy traefik env file
      ansible.builtin.template:
        src: env.j2
        dest: "{{ traefik_stack_dir }}/.env"
        owner: root
        group: root
        mode: 0600
      notify: restart traefik

    - name: Deploy traefik compose
      community.docker.docker_compose_v2:
        project_src: "{{ traefik_stack_dir }}"
        state: present
        pull: always
